// F280 (AS-531): Vite build for the MV3 extension skeleton.
// @crxjs/vite-plugin@2.7.1 handles manifest-driven bundling (popup HTML,
// background service worker, content scripts) the way a plain Vite config
// cannot — it rewrites manifest.json paths into hashed build outputs and
// wires the service worker into an ESM-compatible bundle for MV3.
// Verified against npm registry (`npm view @crxjs/vite-plugin versions`,
// dist-tag latest 2.7.1, peerDependency vite ^3||^4||^5||^6||^7||^8) 2026-08-19.
//
// F344 (M19 scrutiny BLOCKER-5, AS-571): manifest.json's host_permissions,
// content_scripts[].matches and web_accessible_resources[].matches (the
// last generated by crxjs itself from content_scripts) must target the app
// origin the extension code actually talks to at runtime — VITE_APP_URL
// (see src/lib/supabase.ts's APP_URL). The manifest is no longer passed to
// crx({ manifest }) verbatim: we load manifest.json as plain JSON (not a
// static ESM import, since we need to mutate a fresh object per build) and
// programmatically rewrite the origin-scoped fields before handing it off.
//
// `import.meta.env` is not available inside vite.config.ts's own
// evaluation (it's a Node-side config file, not app code bundled by Vite),
// so we use Vite's own `loadEnv` — the documented way to read `.env` files
// at config-authoring time — rather than `dotenv` directly, keeping the
// same `.env` loading precedence (`.env`, `.env.local`, `.env.[mode]`,
// etc.) that the rest of the app relies on. Verified against the current
// Vite config docs for config-time env access (`loadEnv` exported from
// "vite"), vite@8.2.1, 2026-08-26.
import { defineConfig, loadEnv } from "vite";
import react from "@vitejs/plugin-react";
import { crx } from "@crxjs/vite-plugin";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// @crxjs/vite-plugin exports its manifest type only as `ManifestV3Export`,
// a union with `Promise<ManifestV3>` and a function form — too broad for a
// plain synchronous object we read, mutate and pass straight to `crx()`.
// This local shape covers exactly the fields this file reads or writes;
// `[key: string]: unknown` preserves every other manifest field untyped
// (and unmodified) through the rewrite.
interface ExtensionManifest {
  manifest_version: number;
  name: string;
  version: string;
  content_scripts?: Array<{ matches?: string[]; [key: string]: unknown }>;
  host_permissions?: string[];
  [key: string]: unknown;
}

const manifestPath = fileURLToPath(new URL("./manifest.json", import.meta.url));

function readManifest(): ExtensionManifest {
  return JSON.parse(readFileSync(manifestPath, "utf8"));
}

/**
 * Rewrites the three origin-scoped manifest fields (host_permissions,
 * content_scripts[].matches; web_accessible_resources[].matches is derived
 * by crxjs from content_scripts and needs no separate rewrite) to match the
 * configured app origin. Throws if the origin is unparseable.
 */
// Audit SEC-EXT-07: VITE_APP_URL used to be mandatory with no default, so
// every CI build (which has no extension/.env) threw, and the only working
// artifact anyone ever built pointed at localhost. It is now a build-time
// variable with the production origin as its default — set VITE_APP_URL
// (e.g. http://localhost:3000 in extension/.env) to build against another
// deployment. The resolved value is also injected into the bundle via
// `define` below, so the manifest origins and the runtime APP_URL can never
// disagree.
export const DEFAULT_APP_URL = "https://pm-app-beige.vercel.app";

function withAppOrigin(
  manifest: ExtensionManifest,
  appUrl: string,
): ExtensionManifest {
  let origin: string;
  try {
    origin = new URL(appUrl).origin;
  } catch {
    throw new Error(
      `VITE_APP_URL ("${appUrl}") is not a valid URL. It must be an absolute URL ` +
        `(e.g. "https://app.example.com") so the extension manifest's ` +
        `host_permissions and content_scripts origins can be derived from it.`,
    );
  }

  return {
    ...manifest,
    host_permissions: [`${origin}/*`],
    content_scripts: manifest.content_scripts?.map((script) => ({
      ...script,
      matches: script.matches?.map((match) => {
        // Preserve everything after the origin (e.g. "/extension-connect*")
        // while swapping the origin itself for the configured one.
        const path = match.replace(/^https?:\/\/[^/]+/, "");
        return `${origin}${path}`;
      }),
    })),
  };
}

export default defineConfig(({ mode, command }) => {
  const env = loadEnv(mode, process.cwd(), "");
  const appUrl = (env.VITE_APP_URL || DEFAULT_APP_URL).replace(/\/+$/, "");
  const manifest = withAppOrigin(readManifest(), appUrl);

  // Only enforce this at actual build time (not `vite dev`/`--watch` with no
  // env configured yet in some ad-hoc local setup) — but this project has no
  // dev-server mode for the extension (see package.json's "dev": "vite build
  // --watch"), so build-loudness applies uniformly to build and watch.
  void command;

  return {
    plugins: [react(), crx({ manifest })],
    define: {
      "import.meta.env.VITE_APP_URL": JSON.stringify(appUrl),
    },
    build: {
      outDir: "dist",
      emptyOutDir: true,
      rollupOptions: {
        input: {
          popup: "src/popup/index.html",
        },
      },
    },
  };
});
