// Project A — "Nordvik — Website Relaunch" (fixed price): spec + the
// project-specific records the generic builder does not cover.

import type { ProjectSpec } from "./build-project";
import { PROJECT_A_COMPONENTS, PROJECT_A_TASKS } from "./project-a-tasks";

export const PROJECT_A: ProjectSpec = {
  key: "NVWEB",
  name: "Nordvik — Website Relaunch",
  description:
    "New nordvikoutdoor.se on Webflow with a Centra product feed, store locator and a journal. Fixed fee: 874 000 SEK (760 h). Launch before the Black Friday traffic peak.",
  icon: "🚀",
  sidebarPosition: 0,
  billingModel: "fixed_price",
  start: -100, // 2026-06-15
  end: 37, // 2026-10-30
  createdDaysAgo: 106,
  targetLaunch: 37,
  launchConfidence: "at_risk",
  launchNote:
    "Development is ~1 week behind because of the Centra API rate limits. We can still hit 30 October if the store list and category copy land this week.",
  warrantyUntil: 67,
  warrantyTerms: "30 days of bug fixes after launch at no cost. Covers anything that worked on staging at sign-off; new features are change requests.",
  lead: "tom",
  members: [
    { who: "tom", lead: true },
    { who: "anna" },
    { who: "john" },
    { who: "maja" },
    { who: "marko" },
    { who: "nina" },
    { who: "gary" },
    { who: "lisa" },
    { who: "clara" },
    { who: "erik" },
  ],
  roles: [
    { who: "tom", role: "pm", note: "Account lead — your main contact" },
    { who: "anna", role: "team_lead", note: "Delivery lead" },
    { who: "maja", role: "design_lead" },
    { who: "john", role: "webflow_lead" },
    { who: "marko", role: "developer", note: "Centra integration" },
    { who: "maja", role: "designer" },
  ],
  phases: [
    { name: "Discovery", clientDescription: "Workshops, interviews and an audit of today's site — we agree what we're building and why.", state: "done", plannedStart: -100, plannedEnd: -84, actualStart: -100, actualEnd: -84 },
    { name: "Design", clientDescription: "Art direction, design system and every page template in Figma, reviewed with you in two rounds.", state: "done", plannedStart: -80, plannedEnd: -33, actualStart: -80, actualEnd: -26 },
    { name: "Development", clientDescription: "We build the site in Webflow and connect it to Centra so products stay in sync automatically.", state: "active", plannedStart: -30, plannedEnd: 16, actualStart: -30 },
    { name: "Content & QA", clientDescription: "Final copy and images go in, then we test every page on every device.", state: "not_started", plannedStart: 12, plannedEnd: 30 },
    { name: "Launch", clientDescription: "Go-live on nordvikoutdoor.se, redirects, training for your team and 30 days of warranty.", state: "not_started", plannedStart: 30, plannedEnd: 37 },
  ],
  components: PROJECT_A_COMPONENTS,
  customFields: [
    { name: "Figma frame", type: "url" },
    { name: "Webflow page ID", type: "text" },
    { name: "Word count", type: "number" },
    { name: "Needs translation", type: "checkbox" },
  ],
  tasks: PROJECT_A_TASKS,
  dependencies: [
    ["kickoff", "interviews"],
    ["interviews", "ia-signoff"],
    ["seo-audit", "redirects"],
    ["ia-signoff", "moodboard"],
    ["moodboard", "design-system"],
    ["design-system", "home-design"],
    ["home-design", "template-designs"],
    ["template-designs", "webflow-setup"],
    ["webflow-setup", "global-components"],
    ["global-components", "page-home"],
    ["cms-setup", "centra-feed"],
    ["centra-feed", "page-collection-tpl"],
    ["centra-feed", "page-product-tpl"],
    ["store-data", "page-stores"],
    ["category-copy", "page-collection-tpl"],
    ["cr-size-guide", "page-product-tpl"],
    ["browser-qa", "launch-checklist"],
    ["a11y", "launch-checklist"],
    ["redirects", "launch-checklist"],
  ],
  comments: [
    { task: "kickoff", by: "tom", daysAgo: 99, hour: 17, parts: (p) => ["Great session today. Summary + photos of the wall are in Docs → Discovery. ", { mention: p.clara }, " thanks for the fika!"], reactions: [["clara", "❤️"], ["anna", "🎉"]] },
    { task: "kickoff", by: "clara", daysAgo: 98, hour: 9, parts: ["Thank you all — the team was buzzing afterwards. Erik will send the Centra access this week."] },
    { task: "ia-signoff", by: "clara", daysAgo: 84, hour: 14, parts: ["Approved from our side. Let's keep ‘Sustainability’ as a top-level item as discussed."], reactions: [["tom", "👍"]] },
    { task: "home-design", by: "clara", daysAgo: 58, hour: 10, parts: ["Round 1 feedback: the hero feels too dark and we'd like to see product in the first viewport on mobile."] },
    { task: "home-design", by: "maja", daysAgo: 56, hour: 15, parts: (p) => ["Updated in round 2 — brighter autumn footage and a product rail under the hero. ", { mention: p.clara }, " let me know what you think!"] },
    { task: "home-design", by: "maja", daysAgo: 57, hour: 11, internal: true, parts: (p) => [{ mention: p.tom }, " I think we should push back on the product rail — it competes with the campaign. Thoughts?"] },
    { task: "home-design", by: "tom", daysAgo: 57, hour: 12, internal: true, parts: ["Agree it's busy, but it's their #1 KPI. Let's do a slim version and show both."], reactions: [["maja", "👍"]] },
    { task: "home-design", by: "clara", daysAgo: 52, hour: 16, parts: ["Approved! 🎉 Love the new version."], reactions: [["maja", "🎉"], ["tom", "❤️"], ["anna", "🎉"]] },
    { task: "centra-feed", by: "marko", daysAgo: 6, hour: 11, internal: true, parts: (p) => ["Centra caps us at 2 req/s, not 10 as documented. Full sync takes ~40 min instead of 8. ", { mention: p.tom }, " we need to tell Nordvik — this pushes the feed by ~3 days."] },
    { task: "centra-feed", by: "tom", daysAgo: 6, hour: 13, internal: true, parts: ["Thanks — I'll flag it in Friday's update and mark the assumption as invalidated. Can we do incremental syncs after the first full run?"] },
    { task: "centra-feed", by: "marko", daysAgo: 5, hour: 9, internal: true, parts: ["Yes, delta sync on updated_at works. Implementing now."], reactions: [["tom", "🚀"], ["anna", "👍"]] },
    { task: "centra-feed", by: "anna", daysAgo: 2, hour: 10, internal: true, parts: (p) => [{ mention: p.marko }, " how are we looking for Friday? This is now blocking both templates."] },
    { task: "category-copy", by: "gary", daysAgo: 3, hour: 14, parts: (p) => ["All 8 drafts are in the linked doc. ", { mention: p.clara }, " the Footwear intro is a bit longer on purpose — it targets ‘vandringskängor’."] },
    { task: "category-copy", by: "clara", daysAgo: 1, hour: 18, parts: ["Thanks Gary! I'll go through them with Erik tomorrow morning."], reactions: [["gary", "👍"]] },
    { task: "page-sustainability", by: "erik", daysAgo: 2, hour: 11, parts: ["We need to double-check the CO₂ numbers with our supplier before this goes live. Can we hold the ‘Materials’ section?"] },
    { task: "page-sustainability", by: "tom", daysAgo: 2, hour: 13, parts: (p) => ["Of course — we'll keep it on staging. ", { mention: p.erik }, " could you send the verified figures by Monday?"] },
    { task: "store-data", by: "john", daysAgo: 8, hour: 9, parts: (p) => [{ mention: p.erik }, " friendly reminder about the store CSV — the locator is ready to import as soon as we have it."] },
    { task: "store-data", by: "erik", daysAgo: 7, hour: 16, parts: ["Sorry, our ERP export is being fixed by IT. Expect it early next week."] },
    { task: "bug-menu", by: "nina", daysAgo: 4, hour: 10, internal: true, parts: ["Reproduced on iOS 18.2 and Android 15. Screen recording attached."] },
    { task: "bug-menu", by: "john", daysAgo: 1, hour: 15, internal: true, parts: (p) => ["Fixed on a branch, needs the new interaction on the navbar component. ", { mention: p.nina }, " will ping you when it's on staging."] },
    { task: "bug-video", by: "marko", daysAgo: 2, hour: 12, internal: true, parts: ["Re-encoded to H.265 + poster frame. Stutter is gone on my Mac — ready for QA."], reactions: [["nina", "👀"]] },
    { task: "cr-size-guide", by: "clara", daysAgo: 8, hour: 10, parts: ["Approved the quote — thanks for turning it around so fast."] },
    { task: "cr-size-guide", by: "maja", daysAgo: 1, hour: 16, parts: ["First sketch of the size guide drawer is in Figma — jackets first, footwear next."], reactions: [["clara", "👀"]] },
    { task: "page-home", by: "maja", daysAgo: 1, hour: 11, internal: true, parts: (p) => ["Design QA notes: hero headline wraps badly at 1024px, and the product rail needs 24px more top padding. ", { mention: p.john }] },
    { task: "page-product-tpl", by: "clara", daysAgo: 3, hour: 9, parts: ["Can we show ‘Repairable’ as a badge next to the price? It's a big selling point for us."] },
    { task: "redirects", by: "john", daysAgo: 0, hour: 9, internal: true, parts: ["318 of 400 mapped. The old /shop/*?variant= URLs need a regex rule — Webflow supports it."] },
    { task: "training", by: "clara", daysAgo: 4, hour: 12, parts: ["Can we invite our two store managers to the training as well?"] },
    { task: "training", by: "tom", daysAgo: 4, hour: 14, parts: ["Absolutely — up to 6 people is fine. We'll record it too."], reactions: [["clara", "❤️"]] },
  ],
  timePlan: {
    seed: 11,
    periods: [
      { from: -100, to: -81, hoursPerWeek: 26 },
      { from: -80, to: -64, hoursPerWeek: 32 },
      { from: -63, to: -43, hoursPerWeek: 13 }, // Swedish summer holidays
      { from: -42, to: -27, hoursPerWeek: 34 },
      { from: -26, to: 0, hoursPerWeek: 62 },
    ],
  },
  attachments: [
    { task: "home-design", by: "maja", name: "homepage-round2-desktop.png", kind: "png", daysAgo: 56, accent: "#4d6b53" },
    { task: "home-design", by: "maja", name: "homepage-round2-mobile.png", kind: "png", daysAgo: 56, accent: "#4d6b53" },
    { task: "ia-signoff", by: "tom", name: "nordvik-sitemap-v2.pdf", kind: "pdf", daysAgo: 85 },
    { task: "redirects", by: "john", name: "redirect-map-top400.csv", kind: "csv", daysAgo: 1 },
    { task: "bug-menu", by: "nina", name: "mobile-menu-bug.png", kind: "png", daysAgo: 4, accent: "#b45309" },
    { task: "category-copy", by: "gary", name: "category-copy-v1.txt", kind: "txt", daysAgo: 3 },
    { task: "cr-size-guide", by: "maja", name: "size-guide-sketch.png", kind: "png", daysAgo: 1, accent: "#1e3a5f" },
    { task: "seo-audit", by: "john", name: "seo-baseline-audit.pdf", kind: "pdf", daysAgo: 90 },
    { task: "page-sustainability", by: "erik", name: "nordvik-impact-report-2025.pdf", kind: "pdf", daysAgo: 2 },
  ],
};
