-- F195 follow-up fix (AS-360 coverage gap): wire task_activity writes into
-- the SQL-side scheduled recurrence generator.
--
-- F195 wired `public.write_task_activity_entry(..., p_system := true)`
-- into the TypeScript on-completion path
-- (lib/recurrence/generate-next-occurrence.ts, called from
-- moveTaskStatus), but explicitly flagged that F178's pure-SQL,
-- pg_cron-scheduled `generate_due_recurring_occurrences()` function
-- (20260822160000 / corrected in 20260822161000) does NOT write an
-- activity entry for occurrences it generates -- see F195's handoff,
-- "Out-of-scope work needed" (search "scheduled"). That is a real gap
-- for AS-360 ("recurrence-job changes are attributed to the system"): a
-- task auto-generated by the scheduled job (as opposed to someone
-- completing the prior occurrence) currently gets no system-attributed
-- `task_activity` entry.
--
-- This migration closes that gap with `create or replace function`
-- (signature and return shape unchanged -- only the function body gains
-- one more statement per generated occurrence, immediately after the
-- existing `last_occurrence_at` update in the loop body).
--
-- Mirrors generate-next-occurrence.ts's own write exactly (F195, lines
-- ~252-263), for the same reasons documented there:
--   p_task_id   := the NEWLY generated occurrence's id (v_new_id)
--   p_kind      := 'field_changed' (the closed kind vocabulary from F194
--                  has no dedicated "task created" kind; 'field_changed'
--                  on 'due_date' is the closest fit for "this occurrence
--                  now has a due date, set by the system" -- same
--                  rationale as the TS-side write)
--   p_field     := 'due_date'
--   p_old_value := null (the occurrence didn't exist before this insert)
--   p_new_value := to_jsonb(v_next_due) (the computed due date)
--   p_system    := true (system-attributed -- writes actor_id = null,
--                  matching exactly what F195's TypeScript path does for
--                  AS-360; there is no human actor in a cron-triggered
--                  run to attribute this to)
--
-- Called via `perform` (the function returns a row we don't need here);
-- wrapped so a failure to write the activity entry is non-fatal to the
-- occurrence generation itself, matching the "best-effort, non-fatal"
-- posture generate-next-occurrence.ts documents for this exact same
-- write (the occurrence has already been successfully created by the
-- point this call happens) and matching this function's own pre-existing
-- posture for `last_occurrence_at` a few lines above (also best-effort).
create or replace function public.generate_due_recurring_occurrences()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_task record;
  v_next_due date;
  v_root_id uuid;
  v_new_id uuid;
  v_new_position double precision;
  v_generated_count integer := 0;
begin
  for v_task in
    select t.id, t.project_id, t.title, t.description, t.description_json,
           t.priority, t.estimate_minutes, t.due_date, t.author_id,
           t.recurrence, t.recurrence_parent_id
    from tasks t
    join projects p on p.id = t.project_id
    where t.recurrence is not null
      and t.due_date is not null
      -- gate on the task's OWN due_date having arrived, not the computed
      -- next date (fixed in 20260822161000; unchanged here).
      and t.due_date <= current_date
      and t.deleted_at is null
      and p.deleted_at is null
  loop
    v_next_due := public.recurrence_next_due_date(v_task.recurrence, v_task.due_date);

    -- No further occurrence -- invalid/malformed rule, or the series is
    -- exhausted (past `until`, AS-323).
    if v_next_due is null then
      continue;
    end if;

    -- Series root, never the immediately-due task -- same convention
    -- generate-next-occurrence.ts documents, so repeated generations
    -- across the same series all collide against ONE
    -- recurrence_parent_id value in the shared unique constraint.
    v_root_id := coalesce(v_task.recurrence_parent_id, v_task.id);

    select coalesce(max(position), 0) + 1000
      into v_new_position
      from tasks
      where project_id = v_task.project_id
        and status = 'todo'
        and deleted_at is null;

    v_new_id := null;

    -- Same idempotency guarantee AS-320/F177 already established:
    -- ON CONFLICT (recurrence_parent_id, due_date) DO NOTHING against
    -- tasks_recurrence_occurrence_idempotency.
    insert into tasks (
      project_id, title, description, description_json, status, priority,
      estimate_minutes, due_date, author_id, position, recurrence,
      recurrence_parent_id
    )
    values (
      v_task.project_id, v_task.title, v_task.description, v_task.description_json,
      'todo', v_task.priority, v_task.estimate_minutes, v_next_due, v_task.author_id,
      v_new_position, v_task.recurrence, v_root_id
    )
    on conflict (recurrence_parent_id, due_date) do nothing
    returning id into v_new_id;

    if v_new_id is null then
      continue;
    end if;

    -- F176's clone allow-list, ported: checklist items and assignees.
    insert into checklist_items (task_id, content, position)
    select v_new_id, ci.content, ci.position
    from checklist_items ci
    where ci.task_id = v_task.id
    order by ci.position;

    insert into task_assignees (task_id, user_id, assigned_by)
    select v_new_id, ta.user_id, v_task.author_id
    from task_assignees ta
    where ta.task_id = v_task.id;

    update tasks set last_occurrence_at = now() where id = v_root_id;

    -- F195 follow-up (AS-360): system-attributed task_activity entry for
    -- the newly generated occurrence, mirroring generate-next-occurrence
    -- .ts's own write exactly (see this file's top comment). Best-effort
    -- / non-fatal -- a failure here must never abort generation for this
    -- occurrence (already successfully created) or the rest of the loop.
    begin
      perform public.write_task_activity_entry(
        p_task_id  := v_new_id,
        p_kind     := 'field_changed',
        p_field    := 'due_date',
        p_old_value := null,
        p_new_value := to_jsonb(v_next_due),
        p_system   := true
      );
    exception when others then
      raise warning
        'generate_due_recurring_occurrences: write_task_activity_entry failed for task % (non-fatal): %',
        v_new_id, sqlerrm;
    end;

    v_generated_count := v_generated_count + 1;
  end loop;

  return v_generated_count;
end;
$$;

comment on function public.generate_due_recurring_occurrences() is
  'F178 (AS-322): generates the next occurrence for every date-driven '
  'recurring task whose OWN due_date has arrived (today or earlier), '
  'independent of anyone opening the app or completing the current '
  'occurrence. SECURITY DEFINER so the pg_cron job (which runs as the '
  'postgres role) can write regardless of the calling context''s RLS. '
  'Fixed trigger condition in 20260822161000. F195 follow-up '
  '(20260822231000, AS-360): also writes a system-attributed '
  '(actor_id = null) task_activity entry for each newly generated '
  'occurrence, mirroring lib/recurrence/generate-next-occurrence.ts''s '
  'own write.';

-- Grants are idempotent (safe to repeat) -- restated here so this
-- migration is self-contained if ever read in isolation.
revoke all on function public.generate_due_recurring_occurrences() from public;
grant execute on function public.generate_due_recurring_occurrences() to postgres, service_role;
